<a href="https://colab.research.google.com/github/ene23033/repository/blob/master/merge_iitbpv_NASA_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [20]:
df1 = pd.read_csv('/content/IITB-NASA data.csv')

df1.index = pd.to_datetime(df1['timestamp'], format='%d-%m-%Y %H:%M')
df1.head()

,timestamp,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DWN,T2M,WS10M
timestamp,,,,,,
2015-03-01 00:00:00,01-03-2015 00:00,0.0,0.0,0.0,20.78,2.31
2015-03-01 01:00:00,01-03-2015 01:00,0.0,0.0,0.0,20.66,2.44
2015-03-01 02:00:00,01-03-2015 02:00,0.0,0.0,0.0,20.27,2.49
2015-03-01 03:00:00,01-03-2015 03:00,0.0,0.0,0.0,20.08,2.76
2015-03-01 04:00:00,01-03-2015 04:00,0.0,0.0,0.0,19.94,2.82

In [21]:
df2 = pd.read_csv('/content/Final SCADA data(ground).csv')

df2.index = pd.to_datetime(df2['timestamp'], format='%m-%d-%Y %H:%M')
df2.head()

                            timestamp  Active_Power  Temp1  Temp2    poa
timestamp
2015-03-01 00:00:00  03-01-2015 00:00     -0.000023   20.3   20.1 -1.110
2015-03-01 00:05:00  03-01-2015 00:05     -0.000024   20.3   20.1 -0.965
2015-03-01 00:10:00  03-01-2015 00:10     -0.000028   20.4   20.2 -0.887
2015-03-01 00:15:00  03-01-2015 00:15     -0.000025   20.4   20.2 -0.826
2015-03-01 00:20:00  03-01-2015 00:20     -0.000018   20.4   20.3 -0.803

In [23]:
df3 = pd.merge(df1, df2, left_on=df1.index, right_on=df2.index, how='inner')

df3 = df3.drop(columns=['key_0', 'timestamp_y'], axis=1)
df3 = df3.rename(columns={'timestamp_x':'timestamp'})

df3.to_csv('Merged file(ground POA-NASA).csv', index=False)

df3.tail()

,timestamp,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DWN,T2M,WS10M,Active_Power,Temp1,Temp2,poa
17801,30-04-2017 19:00,0.0,0.0,0.0,28.79,3.14,3.700000e-02,28.6,30.3,-1.28
17802,30-04-2017 20:00,0.0,0.0,0.0,27.81,2.32,1.350000e-06,27.7,28.3,-3.13
17803,30-04-2017 21:00,0.0,0.0,0.0,26.97,1.63,-1.140000e-06,27.2,27.9,-2.71
17804,30-04-2017 22:00,0.0,0.0,0.0,26.25,1.35,1.170000e-06,27.1,27.9,-2.64
17805,30-04-2017 23:00,0.0,0.0,0.0,25.75,1.09,4.940000e-07,26.7,27.5,-2.85