<a href="https://colab.research.google.com/github/ene23033/repository/blob/master/Solcast_NASA_AirTemp_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [5]:
df1 = pd.read_csv('/content/IITB-NASA data.csv')
df1.index = pd.to_datetime(df1['timestamp'], format='%d-%m-%Y %H:%M')
df1.head()

,timestamp,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DWN,T2M,WS10M
timestamp,,,,,,
2015-03-01 00:00:00,01-03-2015 00:00,0.0,0.0,0.0,20.78,2.31
2015-03-01 01:00:00,01-03-2015 01:00,0.0,0.0,0.0,20.66,2.44
2015-03-01 02:00:00,01-03-2015 02:00,0.0,0.0,0.0,20.27,2.49
2015-03-01 03:00:00,01-03-2015 03:00,0.0,0.0,0.0,20.08,2.76
2015-03-01 04:00:00,01-03-2015 04:00,0.0,0.0,0.0,19.94,2.82

In [6]:
df2 = pd.read_csv('/content/POA_solcast_SCADA.csv')
df2.index = pd.to_datetime(df2['timestamp'], format='%d-%m-%Y %H:%M')
df2.head()

,air_temp,azimuth,clearsky_dhi,clearsky_dni,clearsky_ghi,dewpoint_temp,dhi,dni,ghi,precipitation_rate,...,zenith,timestamp,Active_Power,Temp1,Temp2,poa,h,beam,sky,Solcast_poa
timestamp,,,,,,,,,,,,,,,,,,,,,
2015-03-01 00:00:00,22,29,0,0,0,18.2,0.0,0.0,0.0,0.4,...,168.0,01-03-2015 00:00,-0.000023,20.3,20.1,-1.110,0.0,0.0,0.0,0.0
2015-03-01 00:05:00,22,24,0,0,0,18.2,0.0,0.0,0.0,0.7,...,168.0,01-03-2015 00:05,-0.000024,20.3,20.1,-0.965,0.0,0.0,0.0,0.0
2015-03-01 00:10:00,22,18,0,0,0,18.2,0.0,0.0,0.0,0.7,...,169.0,01-03-2015 00:10,-0.000028,20.4,20.2,-0.887,0.0,0.0,0.0,0.0
2015-03-01 00:15:00,22,12,0,0,0,18.2,0.0,0.0,0.0,0.7,...,169.0,01-03-2015 00:15,-0.000025,20.4,20.2,-0.826,0.0,0.0,0.0,0.0
2015-03-01 00:20:00,22,5,0,0,0,18.1,0.0,0.0,0.0,0.7,...,169.0,01-03-2015 00:20,-0.000018,20.4,20.3,-0.803,0.0,0.0,0.0,0.0

In [8]:
df3 = pd.merge(df1, df2, left_on=df1.index, right_on=df2.index, how='inner')

df3.to_csv('Merged file(Solcast-NASA).csv', index=False)

df3.tail()

,key_0,timestamp_x,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,ALLSKY_SFC_SW_DWN,T2M,WS10M,air_temp,azimuth,clearsky_dhi,...,zenith,timestamp_y,Active_Power,Temp1,Temp2,poa,h,beam,sky,Solcast_poa
12059,2016-09-01 13:00:00,01-09-2016 13:00,375.02,277.93,744.83,28.47,5.81,29,130,170,...,16.0,01-09-2016 13:00,154.0,41.4,41.4,472.0,13.0,323.802204,392.994752,716.796956
12060,2016-09-01 14:00:00,01-09-2016 14:00,297.19,240.88,629.70,28.29,5.69,29,108,159,...,29.0,01-09-2016 14:00,105.0,48.3,48.3,838.0,14.0,643.671826,154.668727,798.340553
12061,2016-09-01 15:00:00,01-09-2016 15:00,221.04,206.33,447.92,27.79,5.42,28,99,144,...,42.0,01-09-2016 15:00,107.0,37.9,37.9,326.0,15.0,260.067848,283.072953,543.140800
12062,2016-09-01 16:00:00,01-09-2016 16:00,172.44,80.22,241.35,27.09,4.84,28,93,125,...,56.0,01-09-2016 16:00,55.4,34.9,34.9,176.0,16.0,159.055983,217.898080,376.954063
12063,2016-09-01 17:00:00,01-09-2016 17:00,67.38,65.09,89.15,26.21,3.85,28,88,90,...,71.0,01-09-2016 17:00,62.6,35.2,35.2,191.0,17.0,131.312719,87.548336,218.861055